apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: vote
  labels:
    name: redis-deploy
    app: demo-voting-app
    owner: voting.yash

spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app
       
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "64Mi"
          ports:
            - containerPort: 6379
