apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-voting-app.fullname" . }}-worker
  namespace: vote
  labels:
    name: {{ .Values.workerApp.deployment.name }}
    app: {{ .Values.common.appName }}
    owner: voting.yash
spec:
  replicas: {{ .Values.workerApp.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.workerApp.deployment.labelsName }}
      app: {{ .Values.common.appName }}
    
  template:
    metadata:
      name: {{ .Values.workerApp.deployment.labelsName }}
      labels:
        name: {{ .Values.workerApp.deployment.labelsName }}
        app: {{ .Values.common.appName }}
        
    spec:
      containers:
        - name: worker-app
          image: "{{ .Values.workerApp.deployment.image }}:{{ .Values.workerApp.deployment.tag}}"
          resources:
            requests:
              cpu: "{{ .Values.workerApp.deployment.cpu }}"
              memory: "{{ .Values.workerApp.deployment.memory }}"
            limits:
              cpu: "{{ .Values.workerApp.deployment.cpu }}"
              memory: "{{ .Values.workerApp.deployment.memory }}"
